name: genmak_ecom
description: "Genmak Sale Suit"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  sqflite: ^2.3.0
  permission_handler: ^11.1.0
  intl:
  dropdown_textfield: ^1.0.8
  datetime_picker_formfield_new: ^2.1.0
  path: ^1.8.3
  get_storage: ^2.1.1
  image: ^4.1.4
  network_info_plus: ^4.1.0
  flutter_screenutil: ^5.9.0
  path_provider: ^2.1.2
  upgrader: ^9.0.0
  connectivity_plus: ^5.0.2

  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_native_splash:
  # color: "#ffc410"
  background_image: assets/images/background.jpg
  image: assets/images/logo.png
  # color_dark: "#1a1a1a"
  # image_darK: assets/icons/logo.png
  android: true
  ios: true
  web: true
  # android_gravity: center
  # ios_content_mode: center
  web_image_mode: center

  android_12:
    background_image: assets/images/background.jpg
    image: assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
