name: webview_mak_inapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  # flutter_inappwebview: ^5.8.0
  webview_flutter: ^4.4.2
  permission_handler:
  dio: ^5.4.0
  get_storage: ^2.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_native_splash:
  # color: "#5f6496"
  background_image: assets/images/background.jpeg
  image: assets/images/makdairy1.png
  # color_dark: "#1a1a1a"
  # image_darK: assets/icons/logo.png
  android: true
  ios: true
  web: true
  # android_gravity: center
  # ios_content_mode: center
  web_image_mode: center

  android_12:
    background_image: assets/images/background.jpeg
    image: assets/images/makdairy1.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/makdairy1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
