name: genmak_ecom
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  sqflite: ^2.3.0
  permission_handler: ^11.1.0
  dio: ^5.4.0
  printing: ^5.11.1
  intl: ^0.19.0
  dropdown_textfield: ^1.0.8
  datetime_picker_formfield_new: ^2.1.0
  path: ^1.8.3
  get_storage: ^2.1.1
  upgrader: ^8.4.0
  esc_pos_printer_plus: ^0.0.3
  esc_pos_utils_plus: ^2.0.3
  image: ^4.1.4
  ping_discover_network_plus: ^0.0.5
  # another_brother: ^2.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.6
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter

flutter_native_splash:
  # color: "#5f6496"
  background_image: assets/images/background.jpeg
  image: assets/images/makdairy1.png
  # color_dark: "#1a1a1a"
  # image_darK: assets/icons/logo.png
  android: true
  ios: true
  web: true
  # android_gravity: center
  # ios_content_mode: center
  web_image_mode: center

  android_12:
    background_image: assets/images/background.jpeg
    image: assets/images/makdairy1.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  # adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
